[build]
  base = "frontend"
  publish = "dist/frontend"
  command = "npm run build"

# Proxy /api/* إلى Railway
[[redirects]]
  from = "/api/*"
  to = "https://full-stack-system-production.up.railway.app/api/:splat"
  status = 200
  force = true

# دعم Angular Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
